meta_product_name: "Meghan Martin Porfolio"
meta_title: "Meghan Martin - Product Designer & Creative Developer"
meta_description: "Product Designer and Creative Developer specialized in UI/UX Design"
meta_image: "meta1.png"
twitter_account: "@meghanxmartin"
