meta_product_name: "Meghan Martin Porfolio"
meta_title: "Meghan Martin - Product Designer & Creative Developer"
meta_description: "Porfolio of Meghan Martin, product designer and creative developer"
meta_image: "meta.png"
twitter_account: "@meghanxmartin"
